version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    container_name: crossword-client
  server:
    build: ./server
    ports:
      - "8080:8080"
    container_name: crossword-server